# ===================================================================
# 🖥️ CONFIGURATION DU SERVEUR
# ===================================================================
# En local on garde le port 8085, en ligne la plateforme choisira son port automatiquement (via PORT)
server.port=${PORT:8085}

# ===================================================================
# 💾 CONFIGURATION DE LA BASE DE DONNÉES (Hybride Local / Production)
# ===================================================================
# Si SPRING_DATASOURCE_URL existe en ligne, elle sera prise. Sinon, on utilise ta base locale "pharmastock_db"
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pharmastock_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# ☕ CONFIGURATION DE HIBERNATE / JPA
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# ✉️ CONFIGURATION DE SPRING MAIL (Mailtrap)
# ===================================================================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f70570e0e6bbb2
spring.mail.password=f4b7b18f9c841a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true